services:
  - type: web
    name: gimme-quotes-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: TELEGRAM_API_TOKEN
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
